version: "3.9"
services:
  web:
    image: "daily:web"
    ports:
        - 80:80
        - 443:443
    links:
        - "db:daily_db"
    container_name: "daily_web"
  db:
    build: ./db
    image: "daily:db"
    ports:
        - 4306:3306
    expose:
        - 3306
    container_name: "daily_db"
    volumes:
        - db_data:/var/lib/mysql

volumes:
    db_data: